// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/login_history_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/login_history_repository.go -destination=test/mock/mock_login_history_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/abdurrachmanwahed/online-banking/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockLoginHistoryRepository is a mock of LoginHistoryRepository interface.
type MockLoginHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLoginHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockLoginHistoryRepositoryMockRecorder is the mock recorder for MockLoginHistoryRepository.
type MockLoginHistoryRepositoryMockRecorder struct {
	mock *MockLoginHistoryRepository
}

// NewMockLoginHistoryRepository creates a new mock instance.
func NewMockLoginHistoryRepository(ctrl *gomock.Controller) *MockLoginHistoryRepository {
	mock := &MockLoginHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockLoginHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginHistoryRepository) EXPECT() *MockLoginHistoryRepositoryMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockLoginHistoryRepository) GetAll(ctx context.Context, pagination model.Pagination) ([]model.LoginHistory, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, pagination)
	ret0, _ := ret[0].([]model.LoginHistory)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockLoginHistoryRepositoryMockRecorder) GetAll(ctx, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockLoginHistoryRepository)(nil).GetAll), ctx, pagination)
}

// GetByAccountNo mocks base method.
func (m *MockLoginHistoryRepository) GetByAccountNo(ctx context.Context, accountNo int64, pagination model.Pagination) ([]model.LoginHistory, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAccountNo", ctx, accountNo, pagination)
	ret0, _ := ret[0].([]model.LoginHistory)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByAccountNo indicates an expected call of GetByAccountNo.
func (mr *MockLoginHistoryRepositoryMockRecorder) GetByAccountNo(ctx, accountNo, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAccountNo", reflect.TypeOf((*MockLoginHistoryRepository)(nil).GetByAccountNo), ctx, accountNo, pagination)
}

// GetLatestByAccountNo mocks base method.
func (m *MockLoginHistoryRepository) GetLatestByAccountNo(ctx context.Context, accountNo int64) (*model.LoginHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestByAccountNo", ctx, accountNo)
	ret0, _ := ret[0].(*model.LoginHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestByAccountNo indicates an expected call of GetLatestByAccountNo.
func (mr *MockLoginHistoryRepositoryMockRecorder) GetLatestByAccountNo(ctx, accountNo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestByAccountNo", reflect.TypeOf((*MockLoginHistoryRepository)(nil).GetLatestByAccountNo), ctx, accountNo)
}

// RecordLogin mocks base method.
func (m *MockLoginHistoryRepository) RecordLogin(ctx context.Context, accountNo int64, ipAddress string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordLogin", ctx, accountNo, ipAddress)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordLogin indicates an expected call of RecordLogin.
func (mr *MockLoginHistoryRepositoryMockRecorder) RecordLogin(ctx, accountNo, ipAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordLogin", reflect.TypeOf((*MockLoginHistoryRepository)(nil).RecordLogin), ctx, accountNo, ipAddress)
}

// RecordLogout mocks base method.
func (m *MockLoginHistoryRepository) RecordLogout(ctx context.Context, tokenID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordLogout", ctx, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordLogout indicates an expected call of RecordLogout.
func (mr *MockLoginHistoryRepositoryMockRecorder) RecordLogout(ctx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordLogout", reflect.TypeOf((*MockLoginHistoryRepository)(nil).RecordLogout), ctx, tokenID)
}
