// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/transaction_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/transaction_repository.go -destination=test/mock/mock_transaction_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/abdurrachmanwahed/online-banking/internal/model"
	sqlx "github.com/jmoiron/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionRepository is a mock of TransactionRepository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
	isgomock struct{}
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTransactionRepository) Create(ctx context.Context, tx *sqlx.Tx, transaction *model.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, transaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTransactionRepositoryMockRecorder) Create(ctx, tx, transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTransactionRepository)(nil).Create), ctx, tx, transaction)
}

// GetAll mocks base method.
func (m *MockTransactionRepository) GetAll(ctx context.Context, pagination model.Pagination) ([]model.Transaction, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, pagination)
	ret0, _ := ret[0].([]model.Transaction)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockTransactionRepositoryMockRecorder) GetAll(ctx, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockTransactionRepository)(nil).GetAll), ctx, pagination)
}

// GetByAccountNo mocks base method.
func (m *MockTransactionRepository) GetByAccountNo(ctx context.Context, accountNo int64, pagination model.Pagination) ([]model.Transaction, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAccountNo", ctx, accountNo, pagination)
	ret0, _ := ret[0].([]model.Transaction)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByAccountNo indicates an expected call of GetByAccountNo.
func (mr *MockTransactionRepositoryMockRecorder) GetByAccountNo(ctx, accountNo, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAccountNo", reflect.TypeOf((*MockTransactionRepository)(nil).GetByAccountNo), ctx, accountNo, pagination)
}

// GetMonthlySummary mocks base method.
func (m *MockTransactionRepository) GetMonthlySummary(ctx context.Context, accountNo int64, year, month int) (*model.TransactionSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMonthlySummary", ctx, accountNo, year, month)
	ret0, _ := ret[0].(*model.TransactionSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMonthlySummary indicates an expected call of GetMonthlySummary.
func (mr *MockTransactionRepositoryMockRecorder) GetMonthlySummary(ctx, accountNo, year, month any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMonthlySummary", reflect.TypeOf((*MockTransactionRepository)(nil).GetMonthlySummary), ctx, accountNo, year, month)
}

// GetSummary mocks base method.
func (m *MockTransactionRepository) GetSummary(ctx context.Context, accountNo int64) (*model.TransactionSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummary", ctx, accountNo)
	ret0, _ := ret[0].(*model.TransactionSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummary indicates an expected call of GetSummary.
func (mr *MockTransactionRepositoryMockRecorder) GetSummary(ctx, accountNo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummary", reflect.TypeOf((*MockTransactionRepository)(nil).GetSummary), ctx, accountNo)
}
