// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/balance_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/balance_repository.go -destination=test/mock/mock_balance_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	sqlx "github.com/jmoiron/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockBalanceRepository is a mock of BalanceRepository interface.
type MockBalanceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceRepositoryMockRecorder
	isgomock struct{}
}

// MockBalanceRepositoryMockRecorder is the mock recorder for MockBalanceRepository.
type MockBalanceRepositoryMockRecorder struct {
	mock *MockBalanceRepository
}

// NewMockBalanceRepository creates a new mock instance.
func NewMockBalanceRepository(ctrl *gomock.Controller) *MockBalanceRepository {
	mock := &MockBalanceRepository{ctrl: ctrl}
	mock.recorder = &MockBalanceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceRepository) EXPECT() *MockBalanceRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBalanceRepository) Create(ctx context.Context, tx *sqlx.Tx, accountNo int64, accountType string, balance int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, accountNo, accountType, balance)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBalanceRepositoryMockRecorder) Create(ctx, tx, accountNo, accountType, balance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBalanceRepository)(nil).Create), ctx, tx, accountNo, accountType, balance)
}

// Credit mocks base method.
func (m *MockBalanceRepository) Credit(ctx context.Context, tx *sqlx.Tx, accountNo, amount int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Credit", ctx, tx, accountNo, amount)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Credit indicates an expected call of Credit.
func (mr *MockBalanceRepositoryMockRecorder) Credit(ctx, tx, accountNo, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Credit", reflect.TypeOf((*MockBalanceRepository)(nil).Credit), ctx, tx, accountNo, amount)
}

// Debit mocks base method.
func (m *MockBalanceRepository) Debit(ctx context.Context, tx *sqlx.Tx, accountNo, amount int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Debit", ctx, tx, accountNo, amount)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Debit indicates an expected call of Debit.
func (mr *MockBalanceRepositoryMockRecorder) Debit(ctx, tx, accountNo, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debit", reflect.TypeOf((*MockBalanceRepository)(nil).Debit), ctx, tx, accountNo, amount)
}

// GetByAccountNo mocks base method.
func (m *MockBalanceRepository) GetByAccountNo(ctx context.Context, accountNo int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAccountNo", ctx, accountNo)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAccountNo indicates an expected call of GetByAccountNo.
func (mr *MockBalanceRepositoryMockRecorder) GetByAccountNo(ctx, accountNo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAccountNo", reflect.TypeOf((*MockBalanceRepository)(nil).GetByAccountNo), ctx, accountNo)
}
