// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/address_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/address_repository.go -destination=test/mock/mock_address_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/abdurrachmanwahed/online-banking/internal/model"
	sqlx "github.com/jmoiron/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockAddressRepository is a mock of AddressRepository interface.
type MockAddressRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAddressRepositoryMockRecorder
	isgomock struct{}
}

// MockAddressRepositoryMockRecorder is the mock recorder for MockAddressRepository.
type MockAddressRepositoryMockRecorder struct {
	mock *MockAddressRepository
}

// NewMockAddressRepository creates a new mock instance.
func NewMockAddressRepository(ctrl *gomock.Controller) *MockAddressRepository {
	mock := &MockAddressRepository{ctrl: ctrl}
	mock.recorder = &MockAddressRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAddressRepository) EXPECT() *MockAddressRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAddressRepository) Create(ctx context.Context, tx *sqlx.Tx, address *model.Address) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, address)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAddressRepositoryMockRecorder) Create(ctx, tx, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAddressRepository)(nil).Create), ctx, tx, address)
}

// GetByAccountNo mocks base method.
func (m *MockAddressRepository) GetByAccountNo(ctx context.Context, accountNo int64) (*model.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAccountNo", ctx, accountNo)
	ret0, _ := ret[0].(*model.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAccountNo indicates an expected call of GetByAccountNo.
func (mr *MockAddressRepositoryMockRecorder) GetByAccountNo(ctx, accountNo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAccountNo", reflect.TypeOf((*MockAddressRepository)(nil).GetByAccountNo), ctx, accountNo)
}

// Update mocks base method.
func (m *MockAddressRepository) Update(ctx context.Context, address *model.Address) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, address)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAddressRepositoryMockRecorder) Update(ctx, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAddressRepository)(nil).Update), ctx, address)
}
