// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/request_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/request_repository.go -destination=test/mock/mock_request_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/abdurrachmanwahed/online-banking/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRequestRepository is a mock of RequestRepository interface.
type MockRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockRequestRepositoryMockRecorder is the mock recorder for MockRequestRepository.
type MockRequestRepositoryMockRecorder struct {
	mock *MockRequestRepository
}

// NewMockRequestRepository creates a new mock instance.
func NewMockRequestRepository(ctrl *gomock.Controller) *MockRequestRepository {
	mock := &MockRequestRepository{ctrl: ctrl}
	mock.recorder = &MockRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestRepository) EXPECT() *MockRequestRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRequestRepository) Create(ctx context.Context, request *model.MoneyRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRequestRepositoryMockRecorder) Create(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRequestRepository)(nil).Create), ctx, request)
}

// GetAll mocks base method.
func (m *MockRequestRepository) GetAll(ctx context.Context, pagination model.Pagination) ([]model.MoneyRequest, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, pagination)
	ret0, _ := ret[0].([]model.MoneyRequest)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockRequestRepositoryMockRecorder) GetAll(ctx, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockRequestRepository)(nil).GetAll), ctx, pagination)
}

// GetReceivedByAccountNo mocks base method.
func (m *MockRequestRepository) GetReceivedByAccountNo(ctx context.Context, accountNo int64, pagination model.Pagination) ([]model.MoneyRequest, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReceivedByAccountNo", ctx, accountNo, pagination)
	ret0, _ := ret[0].([]model.MoneyRequest)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetReceivedByAccountNo indicates an expected call of GetReceivedByAccountNo.
func (mr *MockRequestRepositoryMockRecorder) GetReceivedByAccountNo(ctx, accountNo, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceivedByAccountNo", reflect.TypeOf((*MockRequestRepository)(nil).GetReceivedByAccountNo), ctx, accountNo, pagination)
}

// MarkAsViewed mocks base method.
func (m *MockRequestRepository) MarkAsViewed(ctx context.Context, requestID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsViewed", ctx, requestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsViewed indicates an expected call of MarkAsViewed.
func (mr *MockRequestRepositoryMockRecorder) MarkAsViewed(ctx, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsViewed", reflect.TypeOf((*MockRequestRepository)(nil).MarkAsViewed), ctx, requestID)
}
