// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/account_type_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/account_type_repository.go -destination=test/mock/mock_account_type_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	sqlx "github.com/jmoiron/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountTypeRepository is a mock of AccountTypeRepository interface.
type MockAccountTypeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccountTypeRepositoryMockRecorder
	isgomock struct{}
}

// MockAccountTypeRepositoryMockRecorder is the mock recorder for MockAccountTypeRepository.
type MockAccountTypeRepositoryMockRecorder struct {
	mock *MockAccountTypeRepository
}

// NewMockAccountTypeRepository creates a new mock instance.
func NewMockAccountTypeRepository(ctrl *gomock.Controller) *MockAccountTypeRepository {
	mock := &MockAccountTypeRepository{ctrl: ctrl}
	mock.recorder = &MockAccountTypeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountTypeRepository) EXPECT() *MockAccountTypeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAccountTypeRepository) Create(ctx context.Context, tx *sqlx.Tx, accountNo int64, accountType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, accountNo, accountType)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAccountTypeRepositoryMockRecorder) Create(ctx, tx, accountNo, accountType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccountTypeRepository)(nil).Create), ctx, tx, accountNo, accountType)
}

// GetByAccountNo mocks base method.
func (m *MockAccountTypeRepository) GetByAccountNo(ctx context.Context, accountNo int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAccountNo", ctx, accountNo)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAccountNo indicates an expected call of GetByAccountNo.
func (mr *MockAccountTypeRepositoryMockRecorder) GetByAccountNo(ctx, accountNo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAccountNo", reflect.TypeOf((*MockAccountTypeRepository)(nil).GetByAccountNo), ctx, accountNo)
}
